version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
          - ./dist

  deploy:
    machine:
      timezone:
        Asia/Shanghai
      enabled: true
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "4a:4b:41:34:a9:fc:94:ae:1e:46:06:2c:8f:c4:b7:b3"
      - run:
          name: Deploy Over SSH
          command: |
            scp -r `pwd`/dist $SSH_USER@$SSH_HOST:$SSH_WEB_DIR
      - run: echo "copy finished"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
